import { Inter } from "next/font/google";
import "../globals.css";
import { ChatProvider } from "../contexts/ChatContext";
import { SocketProvider } from "../contexts/SocketContext";
import { ViewContextProvider } from "../contexts/ViewContext";
import { SettingsProvider } from "../contexts/SettingContext";
import { Toaster } from "react-hot-toast";
import { RunCodeProvider } from "../contexts/RunCodeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<RunCodeProvider>
					<SettingsProvider>
						<ViewContextProvider>
							<ChatProvider>
								<SocketProvider>{children}</SocketProvider>
							</ChatProvider>
						</ViewContextProvider>
					</SettingsProvider>
				</RunCodeProvider>
				<Toaster position="top-right" />
			</body>
		</html>
	);
}
